third/employee/urls.py
from django.urls import path
from . import views

app_name = 'employee'


urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
]

third/third/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]

third/employee/models.py
from django.db import models
from django.utils import timezone


class Department(models.Model):
    name = models.CharField('部署名', max_length=20)
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return self.name


class Club(models.Model):
    name = models.CharField('部活名', max_length=20)
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return self.name


class Employee(models.Model):
    first_name = models.CharField('名', max_length=20)
    last_name = models.CharField('姓', max_length=20)
    email = models.EmailField('メールアドレス', blank=True)
    department = models.ForeignKey(
        Department, verbose_name='部署', on_delete=models.PROTECT,
    )
    club = models.ManyToManyField(
        Club, verbose_name='部活',
    )
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return '{0} {1} {2}'.format(self.last_name, self.first_name, self.department)

third/employee/forms.py
from django import forms
from .models import Club, Department


class SearchForm(forms.Form):
    club = forms.ModelChoiceField(
        queryset=Club.objects, label='サークル', required=False)

    department = forms.ModelChoiceField(
        queryset=Department.objects, label='部署', required=False)

third/employee/views.py
from django.views import generic
from .forms import SearchForm
from .models import Employee

class IndexView(generic.ListView):
    model=Employee

    def get_context_data(self):
        """テンプレートへ渡す辞書の作成"""
        context = super().get_context_data()
        context['form'] = SearchForm(self.request.GET)  
        return context

    def get_queryset(self):
        """テンプレートへ渡す「employee_list」を作成する"""
        form = SearchForm(self.request.GET)
        form.is_valid() 
        queryset = super().get_queryset()

        department = form.cleaned_data['department']
        if department:
            queryset = queryset.filter(department=department)

        club = form.cleaned_data['club']
        if club:
            queryset = queryset.filter(club=club)
        return queryset

third/employee/templates/employee/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>社員管理システム</title>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">社員管理システム</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'employee:index' %}">一覧 </a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:employee_employee_add' %}">社員追加</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

      <div class="container">
          {% block content %}
          {% endblock %}
      </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

third/employee/templates/employee/employee_list.html
{% extends 'employee/base.html' %}

{% block content %}

<form action="" method="GET">
  {{ form }}
  <button type="submit">検索</button>
</form>

<table class="table table-bordered mt-4">
  <thead>
    <tr>
      <th>ID</th>
      <th>姓</th>
      <th>名</th>
      <th>メール</th>
      <th>部署</th>
      <th>部活</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in employee_list %}
    <tr>
      <td>{{ employee.pk }}</td>
      <td>{{ employee.last_name }}</td>
      <td>{{ employee.first_name }}</td>
      <td>{{ employee.email }}</td>
      <td>{{ employee.department }}</td>
      <td>{% for club in employee.club.all %}{{ club }}　{% endfor %}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}