second/diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # path('add/', views.AddView.as_view(), name='add'),
    # path('update/<int:pk>', views.UpdateView.as_view(), name='update'),
    # path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', views.DetailView.as_view(), name='detail'),
]

second/second/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
]

second/diary/models.py
from django.db import models
from django.utils import timezone


class Day(models.Model):
  title = models.CharField('タイトル', max_length=200)
  text = models.TextField('本文')
  date = models.DateTimeField('日付', default=timezone.now)

  def __str__(self):
    return self.title

second/diary/forms.py
from django import forms
from .models import Day

  
class DayCreateForm(forms.ModelForm):
    class Meta:
        model = Day
        fields = '__all__'

second/diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from .forms import DayCreateForm
from .models import Day


class IndexView(generic.ListView):
  model = Day
  paginate_by = 3


class AddView(generic.CreateView):
  model = Day
  form_class = DayCreateForm
  success_url = reverse_lazy('diary:index')


class UpdateView(generic.UpdateView):
  model = Day
  form_class = DayCreateForm
  success_url = reverse_lazy('diary:index')


class DeleteView(generic.DeleteView):
  model = Day
  success_url = reverse_lazy('diary:index')


class DetailView(generic.DetailView):
  model = Day

second/diary/templates/diary/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Diary</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container">
      <nav class="nav">
        <a class="nav-link active" href="{% url 'diary:index' %}">一覧</a>
        {% if user.is_superuser %}
        <a class="nav-link active" href="{% url 'admin:diary_day_add' %}" target="_blank">追加</a>
        {% endif %}
      </nav>
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

second/diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>タイトル</th>
            <td>{{day.title}}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{day.text}}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{day.date}}</td>
        </tr>
    </table>
<p>こちらのデータを削除します</p>
<button type="submit" class="btn btn-primary">送信</button>
{% csrf_token %}
</form>
{% endblock %}

second/diary/templates/diary/day_detail.html
{% extends 'diary/base.html' %} {% block content %}
<table class="table">
  <tr>
    <th>タイトル</th>
    <td>{{day.title}}</td>
  </tr>
  <tr>
    <th>本文</th>
    <td>{{day.text | linebreaksbr}}</td>
  </tr>
  <tr>
    <th>日付</th>
    <td>{{day.date}}</td>
  </tr>
</table>
{% endblock %}

second/diary/templates/diary/day_form.html
{% extends 'diary/base.html' %} {% block content %}
<form action="" method="POST">
  <table class="table">
    <tr>
      <th>タイトル</th>
      <td>{{form.title}}</td>
    </tr>
    <tr>
      <th>本文</th>
      <td>{{form.text}}</td>
    </tr>
    <tr>
      <th>日付</th>
      <td>{{form.date}}</td>
    </tr>
  </table>
  <button type="submit" class="btn btn-primary">送信</button>
  {% csrf_token %}
</form>
{% endblock %}

second/diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}
{% block content %}
<h1>日記一覧</h1>
<table class="table">
<thead>
    <tr>
        <th>タイトル</th>
        <th>日付</th>
        <th></th>
        <th></th>
    </tr>
</thead>
<tbody>
  {% for day in day_list %}
  <tr>
    <td><a href="{% url 'diary:detail' day.pk %}">{{day.title}}</a></td>
    <td>{{day.date}}</td>
    <td>
      {% if user.is_superuser %}
      <a href="{% url 'admin:diary_day_change' day.pk %}" target="_blank">更新</a>
      {% endif %}
    </td>
    <td>
      {% if user.is_superuser %}
      <a href="{% url 'admin:diary_day_delete' day.pk %}" target="_blank">削除</a>
      {% endif %}
    </td>
  </tr>
  {% endfor %}
</tbody>
</tbale>
{% include 'diary/page1.html' %}
{% endblock %}

second/diary/templates/diary/page1.html
{% if page_obj.has_previous %}
<a href="?page={{page_obj.previous_page_number}}">前へ</a>
{% endif %}

{% if page_obj.has_next %}
<a href="?page={{page_obj.next_page_number}}">次へ</a>
{% endif %}